/* 
创建票务系统元数据表的脚本。
*/

DROP TABLE T_M_USERTYPE;
DROP TABLE T_M_CARDTYPE;
DROP TABLE T_M_PAYTYPE;
DROP TABLE T_M_STATE;

/*
用户类型表
  1：普通用户
  2：VIP
*/
CREATE TABLE T_M_USERTYPE (
  TYPE_ID INT NOT NULL,
  TYPE_DESC VARCHAR(100),
  PRIMARY KEY (TYPE_ID)
);
INSERT INTO T_M_USERTYPE VALUES(1, "NORMAL USER, NULL ALSO MEANS NORMAL USER");
INSERT INTO T_M_USERTYPE VALUES(2, "VIP USER");


/*
卡类型表（基本类型为2的n次方，组合类型为基本类型按位或）
  1：有效期型
  2：余额型
  4：计数型
  8: 单日卡（进场8小时后失效）
  16: 工作人员卡（随时出入）
  3：有效期加余额型
  5：有效期加计数型
*/
CREATE TABLE T_M_CARDTYPE (
  TYPE_ID INT NOT NULL,
  TYPE_DESC VARCHAR(100),
  PRIMARY KEY (TYPE_ID)
);
INSERT INTO T_M_CARDTYPE VALUES(1, "VALID DATE");
INSERT INTO T_M_CARDTYPE VALUES(2, "BALANCE");
INSERT INTO T_M_CARDTYPE VALUES(4, "REMAIN TIMES");
INSERT INTO T_M_CARDTYPE VALUES(8, "SINGLE DAY (TWO CHEK-INS MUST WITHIN 8 HOURS)");
INSERT INTO T_M_CARDTYPE VALUES(16, "STAFF");
INSERT INTO T_M_CARDTYPE VALUES(3, "VALID DATE + BALANCE");
INSERT INTO T_M_CARDTYPE VALUES(5, "VALID DATE + REMAIN TIMES");


/*
支付类型表
  1：用户账户支付
  11：卡支付，剩余次数方式
  12：卡支付，余额方式
*/
CREATE TABLE T_M_PAYTYPE (
  TYPE_ID INT NOT NULL,
  TYPE_DESC VARCHAR(100),
  PRIMARY KEY (TYPE_ID)
);
INSERT INTO T_M_PAYTYPE VALUES(1, "USER BALANCE PAY");
INSERT INTO T_M_PAYTYPE VALUES(11, "CARD PAY, TIMES");
INSERT INTO T_M_PAYTYPE VALUES(12, "CARD PAY, BALANCE");


/*
状态表，该表适用于用户状态，卡状态，活动状态以及订单状态
  1：正常态
  9：挂起状态（可适用于用户账户被盗，卡挂失，活动延期等情况）
  -1：已删除（删除记录时尽量不真删除，而是改状态，以保留历史数据）
  101：未支付（只用于订单状态）
  102：已支付（只用于订单状态）
*/
CREATE TABLE T_M_STATE (
  STATE_ID INT NOT NULL,
  STATE_DESC VARCHAR(100),
  PRIMARY KEY (STATE_ID)
);
INSERT INTO T_M_STATE VALUES(1, "NORMAL");
INSERT INTO T_M_STATE VALUES(9, "SUSPENDED");
INSERT INTO T_M_STATE VALUES(-1, "DELETED");
INSERT INTO T_M_STATE VALUES(101, "NOT PAIED");
INSERT INTO T_M_STATE VALUES(102, "PAIED");
